# Production image for Google Cloud Run (Next.js standalone output).
# NEXT_PUBLIC_* must be passed as build args — they are inlined at build time.

FROM node:24-alpine AS builder

WORKDIR /app

ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_PRIVY_APP_ID
ARG NEXT_PUBLIC_REOWN_PROJECT_ID
ARG NEXT_PUBLIC_ALCHEMY_API_KEY
ARG NEXT_PUBLIC_BASE_RPC_URL
ARG NEXT_PUBLIC_LOGODEV_TOKEN
ARG NEXT_PUBLIC_PIMLICO_API_KEY
ARG NEXT_PUBLIC_PAY_GAS_IN_USDC
ARG NEXT_PUBLIC_LIFI_INTEGRATOR
ARG NEXT_PUBLIC_LIFI_FEE
ARG NEXT_PUBLIC_LIFI_API_KEY
ARG NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY
ARG NEXT_PUBLIC_STRIPE_PRICE_PRO_YEARLY
ARG NEXT_PUBLIC_STRIPE_PRICE_ULTIMATE_MONTHLY
ARG NEXT_PUBLIC_STRIPE_PRICE_ULTIMATE_YEARLY

ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_PRIVY_APP_ID=$NEXT_PUBLIC_PRIVY_APP_ID
ENV NEXT_PUBLIC_REOWN_PROJECT_ID=$NEXT_PUBLIC_REOWN_PROJECT_ID
ENV NEXT_PUBLIC_ALCHEMY_API_KEY=$NEXT_PUBLIC_ALCHEMY_API_KEY
ENV NEXT_PUBLIC_BASE_RPC_URL=$NEXT_PUBLIC_BASE_RPC_URL
ENV NEXT_PUBLIC_LOGODEV_TOKEN=$NEXT_PUBLIC_LOGODEV_TOKEN
ENV NEXT_PUBLIC_PIMLICO_API_KEY=$NEXT_PUBLIC_PIMLICO_API_KEY
ENV NEXT_PUBLIC_PAY_GAS_IN_USDC=$NEXT_PUBLIC_PAY_GAS_IN_USDC
ENV NEXT_PUBLIC_LIFI_INTEGRATOR=$NEXT_PUBLIC_LIFI_INTEGRATOR
ENV NEXT_PUBLIC_LIFI_FEE=$NEXT_PUBLIC_LIFI_FEE
ENV NEXT_PUBLIC_LIFI_API_KEY=$NEXT_PUBLIC_LIFI_API_KEY
ENV NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY=$NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY
ENV NEXT_PUBLIC_STRIPE_PRICE_PRO_YEARLY=$NEXT_PUBLIC_STRIPE_PRICE_PRO_YEARLY
ENV NEXT_PUBLIC_STRIPE_PRICE_ULTIMATE_MONTHLY=$NEXT_PUBLIC_STRIPE_PRICE_ULTIMATE_MONTHLY
ENV NEXT_PUBLIC_STRIPE_PRICE_ULTIMATE_YEARLY=$NEXT_PUBLIC_STRIPE_PRICE_ULTIMATE_YEARLY
ENV BUILD_MODE=standalone

COPY package*.json ./
COPY tsconfig.json next.config.ts eslint.config.mjs postcss.config.mjs ./

RUN npm ci --legacy-peer-deps

COPY app ./app
COPY public ./public
COPY proxy.ts ./

RUN npm run build

FROM node:24-alpine AS runner

WORKDIR /app

RUN apk add --no-cache dumb-init curl

ENV NODE_ENV=production
ENV PORT=8080
ENV HOSTNAME=0.0.0.0

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD curl -fsS "http://127.0.0.1:${PORT}/" > /dev/null || exit 1

ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "server.js"]
